### ISSUE TITLE
apply colors for svg export

### ISSUE THREAD

**Issue by poetaster** [anvaka/lsystem#17]
I just noticed that colors applied in rendering a scene don't apply to the svg output. I'll see if I spot it but thought I'd not it here.

**Comment by anvaka** [comment]
I see what is going on. It is a bug and it has at least two components to it. 

The first part is that I didn't set explicit order of expression evaluation [here](https://github.com/anvaka/lsystem/commit/7e9d8255733dd1288b3f875e9174c133af1018f5). That one is easy to fix and I already did it. 

The second part is that w-gl library, which performs [actual SVG generation](https://github.com/anvaka/w-gl/blob/38bfed37d54981ac409e1a9ec34d876422c663e1/src/save/svg.ts#L142) based scene elements, assumes the entire line has the same color. This is no longer true, as each individual vertex of the line could potentially change color with `setColor` command. 

Second part is much trickier to fix. I have a suspicion that it should be fixed by creating one [elementGraph](https://github.com/anvaka/w-gl/blob/38bfed37d54981ac409e1a9ec34d876422c663e1/src/save/svg.ts#L146) instance for each unique color. This is a bit heavy operation in terms CPU + RAM, and should likely be done conditionally based on LineCollectionTrait. I'll play a bit more in this area

**Comment by anvaka** [comment]
Yup, that was it. Fixed [here](https://github.com/anvaka/w-gl/commit/cd4de638a5ad4f44c052844a58ad11bd57717476). Deployed version should have correct colors now.

**Comment by poetaster** [comment]
Thank you very much! I'm not sure I grokked on initial reading, but it seems that moving to multiColorSegment actually yielded an elegant recursion (line 188), or? 

In any case, this is great! Thank you again.
